<?php
/**
 * @Author: Alex Dong
 * @Date:   2020-04-15 18:40:02
 * @Last Modified by:   Alex Dong
 * @Last Modified time: 2020-04-15 18:52:58
 */
$helper = $this->helper('Magepow\Instagram\Helper\Data');
if(!$helper->getConfigModule('general/enabled')) return;
$selector   = 'instagram-' . uniqid();
$username   = $helper->getConfigModule('general/username');
if(!$username) return;
$accessToken   = $helper->getConfigModule('general/accessToken');
if($accessToken) $accessToken = "accessToken: '$accessToken',";
$limit      = $helper->getConfigModule('general/limit');
?>
<div class="social-feed instagram clearfix <?php /* @escapeNotVerified */ echo $selector ?>">
    <section class="section-content"
        <?php foreach ($this->getFrontendCfg() as $opt) :?>
            data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
        <?php endforeach;?>
    >
        <h4 class="title"><?php /* @escapeNotVerified */ echo $this->getTitle() ?></h4>
    </section>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'magepow/slick',
        'magepow/instagram',
        ], function($, slick, instagram){
            $('.<?php echo $selector?> .section-content').instagram({
                username: '<?php echo $username ?>',
                limit: <?php echo $limit ?>,
                <?php echo $accessToken ?>
                lazy : false,
                afterload: function() {
                    var el = $(this).find('.social-list');
                    if( el.length ){
                        if( !$(this).data( 'vertical') && $('body').hasClass('rtl') ){
                            el.attr('dir', 'rtl');
                            $(this).data( 'rtl', true );
                        } 
                        var options = $(this).data();
                        el.slick(options);
                    }   
            
                }
            }) 
    });
</script>
